---
# Non-sensitive global variables
app_name: devops-app
docker_image: 3llimi/devops-info-service
docker_tag: latest
app_port: 8000
app_internal_port: 8000
compose_project_dir: "/opt/{{ app_name }}"
docker_compose_version: "3.8"

docker_user: vagrant
deploy_user: vagrant

common_packages:
  - python3-pip
  - curl
  - git
  - vim
  - htop
  - wget
  - unzip
  - ca-certificates
  - gnupg
  - lsb-release
  - apt-transport-https

# vault-encrypted value in production:
app_secret_key: "use-vault-in-production"
