---
app_name: devops-python
docker_image: 3llimi/devops-info-service
docker_tag: latest
app_port: 8000
app_internal_port: 8000
compose_project_dir: "/opt/devops-python"
app_environment:
  APP_LANG: python
